[package]
name = "Lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6"
dot = "0.1"
bitvec = "1.0.1"
clap = {version = "4.5", features = ["derive"]}

[profile.release]
debug = true  # Enables DWARF debug info for Valgrind
