[package]
name = "lexer"
version = "1.0.0"
edition = "2021"

[dependencies]
petgraph = "0.7"
dot = "0.1"
bitvec = "1.0.1"
clap = {version = "4.5", features = ["derive"]}
egui_graphs = "0.24.0"
egui = "0.31.1"
eframe = "0.31.1"

[profile.release]
debug = true  # Enables DWARF debug info
